require("includes.common").setup()
require("includes.treesitter").setup()
require("includes.keybindings").setup()
require("includes.formatting").setup()
require("includes.completion").setup()
require("includes.lsp").setup()
require("includes.theming").setup()
