# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];
  boot.initrd.availableKernelModules = [
    "usb_storage"
    "xhci_pci"
    "usbhid"
    "sd_mod"
    "ahci"
    "nvme"
  ];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-intel"];
  boot.extraModulePackages = [];
  fileSystems."/" = {
    device = "/dev/disk/by-uuid/11fc49d2-df53-4f0b-8a17-4f6da341da4f";
    fsType = "ext4";
  };
  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/6D41-D3E4";
    fsType = "vfat";
    options = ["fmask=0077" "dmask=0077"];
  };
  swapDevices = [
    {device = "/dev/disk/by-uuid/ceba2ede-58d4-4acf-8d80-bea673024ac1";}
  ];
  networking.interfaces."enp5s0".ipv4.addresses = [
    {
      address = "192.168.50.3";
      prefixLength = 24;
    }
  ];
  networking.defaultGateway = "192.168.50.1";
  networking.nameservers = ["1.1.1.1" "8.8.8.8"];
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
