AllCops:
  TargetRubyVersion: '3.0'
  NewCops: enable

Gemspec/RequiredRubyVersion:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/GlobalVars:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/StringConcatenation:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Style/MissingRespondToMissing:
  Enabled: false

Lint/MissingSuper:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Layout/LeadingCommentSpace:
  Enabled: false
